name: krzemienski/awesome-video/build
on:
  push:
    branches:
    - master
env:
  GH_TOKEN: xxxxd4ef
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  CUSTOM_DOMAIN: awesome.video
  CONFIG_FILE: mkdocs.yml
  EXTRA_PACKAGES: build-base
  REQUIREMENTS: requirements.txt
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
jobs:
  awesomebot:
    runs-on: ubuntu-latest
    container:
      image: ruby:latest
    steps:
    - uses: actions/checkout@v3.5.0
    - name: install awesomebot
      run: gem install awesome_bot
    - name: run awesomebot
      run: awesome_bot contents.json --allow-ssl --allow-redirect -a 403,503,429,404,500,443
